"use client";

import { useState } from "react";
import { PRD, APIEndpoint } from "@/types/prd";

interface PRDOutputProps {
  prd: PRD;
  isDemo: boolean;
}

const SECTIONS = {
  summary: { icon: "🎯", label: "Summary", accent: "#8b5cf6" },
  stories: { icon: "📋", label: "User Stories", accent: "#38bdf8" },
  api: { icon: "🔌", label: "REST API Spec", accent: "#34d399" },
  ui: { icon: "🎨", label: "UI Components", accent: "#fb923c" },
  acceptance: { icon: "✅", label: "Acceptance Criteria", accent: "#e879f9" },
};

function CopyBtn({ text, id }: { text: string; id: string }) {
  const [copied, setCopied] = useState(false);
  return (
    <div
      id={id}
      role="button"
      tabIndex={0}
      onClick={(e) => { e.stopPropagation(); navigator.clipboard.writeText(text); setCopied(true); setTimeout(() => setCopied(false), 2000); }}
      onKeyDown={(e) => { if (e.key === "Enter") e.currentTarget.click(); }}
      className="text-xs px-3 py-1 rounded-lg transition-all cursor-pointer select-none"
      style={{
        background: copied ? "rgba(139,92,246,0.25)" : "rgba(255,255,255,0.05)",
        border: `1px solid ${copied ? "rgba(139,92,246,0.5)" : "rgba(255,255,255,0.09)"}`,
        color: copied ? "#a78bfa" : "#475569",
      }}
    >
      {copied ? "✓ Copied" : "Copy"}
    </div>
  );
}

function SectionCard({ sectionKey, children, copyText }: {
  sectionKey: keyof typeof SECTIONS;
  children: React.ReactNode;
  copyText: string;
}) {
  const [open, setOpen] = useState(true);
  const meta = SECTIONS[sectionKey];

  return (
    <div
      className="glass-section overflow-hidden fade-in"
      style={{ borderLeftWidth: "3px", borderLeftColor: meta.accent }}
    >
      {/* Header */}
      <button
        onClick={() => setOpen(!open)}
        className="w-full flex items-center justify-between px-5 py-4 text-left"
        style={{ borderBottom: open ? "1px solid rgba(255,255,255,0.06)" : "none" }}
      >
        <div className="flex items-center gap-3">
          <div
            className="w-9 h-9 rounded-xl flex items-center justify-center text-lg shrink-0"
            style={{ background: `${meta.accent}18`, border: `1px solid ${meta.accent}30` }}
          >
            {meta.icon}
          </div>
          <span className="font-semibold text-sm" style={{ color: meta.accent }}>
            {meta.label}
          </span>
        </div>
        <div className="flex items-center gap-2.5">
          <CopyBtn text={copyText} id={`copy-${sectionKey}`} />
          <span
            className="text-xs transition-transform duration-300"
            style={{ color: "#475569", display: "inline-block", transform: open ? "rotate(180deg)" : "none" }}
          >
            ▼
          </span>
        </div>
      </button>

      <div className={`section-body ${open ? "open" : "closed"}`}>
        <div className="px-5 py-4">{children}</div>
      </div>
    </div>
  );
}

function MethodBadge({ method }: { method: APIEndpoint["method"] }) {
  return <span className={`badge badge-${method.toLowerCase()}`}>{method}</span>;
}

export default function PRDOutput({ prd, isDemo }: PRDOutputProps) {
  const allMarkdown = [
    `# ${prd.title}`,
    `\n## Summary\n${prd.summary}`,
    `\n## User Stories\n${prd.userStories.map(s => `- As ${s.persona}, I want to ${s.goal}, so that ${s.benefit}.`).join("\n")}`,
    `\n## REST API Spec\n${prd.apiSpec.map(e => `### ${e.method} ${e.path}\n${e.description}`).join("\n\n")}`,
    `\n## UI Components\n${prd.uiComponents.map(c => `- **${c.name}**: ${c.description}\n  Props: ${c.props.join(", ")}`).join("\n")}`,
    `\n## Acceptance Criteria\n${prd.acceptanceCriteria.map(a => `**${a.id}**\n- Given ${a.given}\n- When ${a.when}\n- Then ${a.then}`).join("\n\n")}`,
    `\n---\n*Generated by Chisel · ${new Date(prd.metadata.generatedAt).toLocaleString()}*`,
  ].join("\n");

  function downloadMd() {
    const blob = new Blob([allMarkdown], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url; a.download = `${prd.title.replace(/\s+/g, "-").toLowerCase()}.md`; a.click();
  }

  const storyCopy = prd.userStories.map(s => `As ${s.persona}, I want to ${s.goal}, so that ${s.benefit}.`).join("\n");
  const apiCopy = prd.apiSpec.map(e => `${e.method} ${e.path} — ${e.description}`).join("\n");
  const uiCopy = prd.uiComponents.map(c => `${c.name}: ${c.description}`).join("\n");
  const acceptanceCopy = prd.acceptanceCriteria.map(a => `Given ${a.given} | When ${a.when} | Then ${a.then}`).join("\n");

  return (
    <div className="space-y-3 fade-in relative z-10">

      {/* Output header */}
      <div className="flex items-start justify-between gap-4 mb-2">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="text-xs font-bold uppercase tracking-widest" style={{ color: "#8b5cf6" }}>Step 2 — Your Spec</span>
            {isDemo && <div className="chip chip-amber">⚡ Demo Mode</div>}
          </div>
          <h2 className="text-xl font-bold" style={{ color: "#f0f4ff", letterSpacing: "-0.02em" }}>
            {prd.title}
          </h2>
          <p className="text-xs mt-1" style={{ color: "#475569" }}>
            {prd.metadata.estimatedEffort} · {prd.userStories.length} stories ·{" "}
            {prd.apiSpec.length} endpoints · {prd.uiComponents.length} components ·{" "}
            {prd.acceptanceCriteria.length} criteria
          </p>
        </div>
      </div>

      {/* 1 — Summary */}
      <SectionCard sectionKey="summary" copyText={prd.summary}>
        <p className="text-sm leading-relaxed mb-4" style={{ color: "#cbd5e1" }}>{prd.summary}</p>
        <div className="flex gap-2 flex-wrap">
          {[
            { label: "Tone", value: prd.metadata.tone },
            { label: "Audience", value: prd.metadata.audience },
            { label: "Effort", value: prd.metadata.estimatedEffort },
          ].map((m) => (
            <div key={m.label} className="chip chip-violet">
              <span style={{ opacity: 0.6 }}>{m.label}:</span> {m.value}
            </div>
          ))}
        </div>
      </SectionCard>

      {/* 2 — User Stories */}
      <SectionCard sectionKey="stories" copyText={storyCopy}>
        <div className="space-y-3">
          {prd.userStories.map((s) => (
            <div key={s.id} className="flex gap-3 items-start">
              <span
                className="shrink-0 text-xs font-mono px-2 py-0.5 rounded-md mt-0.5"
                style={{ background: "rgba(56,189,248,0.1)", color: "#38bdf8", border: "1px solid rgba(56,189,248,0.2)" }}
              >
                {s.id}
              </span>
              <p className="text-sm leading-relaxed" style={{ color: "#cbd5e1" }}>
                <span style={{ color: "#64748b" }}>As </span>
                <strong style={{ color: "#e2e8f0" }}>{s.persona}</strong>
                <span style={{ color: "#64748b" }}>, I want to </span>
                <span>{s.goal}</span>
                <span style={{ color: "#64748b" }}>, so that </span>
                <span>{s.benefit}.</span>
              </p>
            </div>
          ))}
        </div>
      </SectionCard>

      {/* 3 — REST API */}
      <SectionCard sectionKey="api" copyText={apiCopy}>
        <div className="space-y-4">
          {prd.apiSpec.map((ep, i) => (
            <div key={i} className="rounded-xl overflow-hidden" style={{ border: "1px solid rgba(52,211,153,0.12)" }}>
              {/* Endpoint header */}
              <div className="flex items-center gap-2.5 px-4 py-3 flex-wrap" style={{ background: "rgba(52,211,153,0.05)" }}>
                <MethodBadge method={ep.method} />
                <code className="text-sm font-mono" style={{ color: "#e2e8f0" }}>{ep.path}</code>
              </div>
              <div className="px-4 py-3 space-y-3" style={{ background: "rgba(0,0,0,0.25)" }}>
                <p className="text-xs" style={{ color: "#64748b" }}>{ep.description}</p>

                {ep.requestBody && (
                  <div>
                    <div className="text-xs font-semibold uppercase tracking-widest mb-1.5" style={{ color: "#475569" }}>Body</div>
                    <div className="code-block p-3 space-y-1">
                      {Object.entries(ep.requestBody).map(([k, v]) => (
                        <div key={k} className="flex gap-2">
                          <span style={{ color: "#38bdf8" }}>{k}</span>
                          <span style={{ color: "#475569" }}>:</span>
                          <span style={{ color: "#94a3b8" }}>{v}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                <div>
                  <div className="text-xs font-semibold uppercase tracking-widest mb-1.5" style={{ color: "#475569" }}>Response</div>
                  <div className="code-block p-3 space-y-1">
                    {Object.entries(ep.responseBody).map(([k, v]) => (
                      <div key={k} className="flex gap-2">
                        <span style={{ color: "#34d399" }}>{k}</span>
                        <span style={{ color: "#475569" }}>:</span>
                        <span style={{ color: "#94a3b8" }}>{v}</span>
                      </div>
                    ))}
                  </div>
                </div>

                <div className="flex gap-1.5 flex-wrap pt-1">
                  {ep.statusCodes.map((sc) => (
                    <span
                      key={sc.code}
                      className="text-xs px-2 py-0.5 rounded-md"
                      style={sc.code < 300 ? { background: "rgba(52,211,153,0.1)", color: "#34d399", border: "1px solid rgba(52,211,153,0.2)" } : sc.code < 400 ? { background: "rgba(251,191,36,0.1)", color: "#fbbf24", border: "1px solid rgba(251,191,36,0.2)" } : { background: "rgba(248,113,113,0.1)", color: "#f87171", border: "1px solid rgba(248,113,113,0.2)" }}
                    >
                      {sc.code} {sc.description}
                    </span>
                  ))}
                </div>
              </div>
            </div>
          ))}
        </div>
      </SectionCard>

      {/* 4 — UI Components */}
      <SectionCard sectionKey="ui" copyText={uiCopy}>
        <div className="grid md:grid-cols-2 gap-3">
          {prd.uiComponents.map((c) => (
            <div
              key={c.name}
              className="rounded-xl p-4"
              style={{ background: "rgba(251,146,60,0.05)", border: "1px solid rgba(251,146,60,0.14)" }}
            >
              <div className="font-bold text-sm mb-1.5" style={{ color: "#fb923c", fontFamily: "monospace" }}>
                &lt;{c.name} /&gt;
              </div>
              <p className="text-xs leading-relaxed mb-3" style={{ color: "#64748b" }}>{c.description}</p>
              <div className="flex flex-wrap gap-1.5">
                {c.props.map((p) => (
                  <span key={p} className="text-xs px-2 py-0.5 rounded" style={{ background: "rgba(251,146,60,0.1)", color: "#fdba74", fontFamily: "monospace", border: "1px solid rgba(251,146,60,0.15)" }}>
                    {p}
                  </span>
                ))}
              </div>
            </div>
          ))}
        </div>
      </SectionCard>

      {/* 5 — Acceptance Criteria */}
      <SectionCard sectionKey="acceptance" copyText={acceptanceCopy}>
        <div className="space-y-3">
          {prd.acceptanceCriteria.map((ac) => (
            <div key={ac.id} className="rounded-xl p-4" style={{ background: "rgba(232,121,249,0.04)", border: "1px solid rgba(232,121,249,0.12)" }}>
              <span className="text-xs font-mono px-2 py-0.5 rounded-md inline-block mb-3" style={{ background: "rgba(232,121,249,0.12)", color: "#e879f9", border: "1px solid rgba(232,121,249,0.2)" }}>
                {ac.id}
              </span>
              <div className="space-y-1.5 text-sm">
                {[{ lbl: "Given", val: ac.given }, { lbl: "When", val: ac.when }, { lbl: "Then", val: ac.then }].map((r) => (
                  <div key={r.lbl} className="flex gap-2">
                    <span className="shrink-0 font-semibold w-10" style={{ color: "#64748b" }}>{r.lbl}</span>
                    <span style={{ color: "#cbd5e1" }}>{r.val}</span>
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>
      </SectionCard>

      {/* Export Bar */}
      <div className="glass p-4 flex items-center justify-between gap-3 flex-wrap fade-in">
        <div className="text-xs" style={{ color: "#475569" }}>
          ⌁ Chiseled by{" "}
          <a href="https://github.com/atharva-b" target="_blank" rel="noopener" style={{ color: "#8b5cf6" }}>
            Atharva Bagul
          </a>{" "}
          · {new Date(prd.metadata.generatedAt).toLocaleTimeString()}
        </div>
        <div className="flex gap-2 flex-wrap">
          <button
            id="copy-all-btn"
            onClick={() => navigator.clipboard.writeText(allMarkdown)}
            className="btn-ghost text-xs px-4 py-2"
          >
            Copy All
          </button>
          <button
            id="export-md-btn"
            onClick={downloadMd}
            className="btn-ghost text-xs px-4 py-2"
          >
            ↓ Export .md
          </button>
          <button
            id="share-btn"
            onClick={() => navigator.clipboard.writeText(window.location.href)}
            className="btn-sky text-xs px-4 py-2"
          >
            Share Chisel ↗
          </button>
        </div>
      </div>
    </div>
  );
}
